Prototipos/Controllers/PublicarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataContracts;
using DataLogic;
using Prototipos.Models;

namespace Prototipos.Controllers
{
    public class PublicarController : Controller
    {
        // GET: Publicar
        DatosSession session = new DatosSession();
        public ActionResult Index()
        {
            return View();
        }

        #region Eventos

        public ActionResult eventoMantenimiento()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                ViewBag.Render = true;
            }
            else
            {
                ViewBag.Render = false;
            }

                return View(Publicar.listarEventos());
        }

        [ValidateInput(false)]
        public ActionResult agregarEvento()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return View();
            }
            else
            {
                return RedirectToAction("getHome", "Home");
            }

        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult agregarEvento(Eventos _eve)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                if (ModelState.IsValid)
                {
                    Publicar.AgregarEvento(_eve);
                    return RedirectToAction("eventoMantenimiento");
                }
                return View();
            }
            else
            {
                return RedirectToAction("getHome", "Home");
            }

        }

        [ValidateInput(false)]
        public ActionResult modificarEvento(int? id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
                }

                Eventos eve = Publicar.visualizarMantenimientoEventos(id);

                return View(eve);
            }
            else
            {
                return RedirectToAction("getHome", "Home");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult modificarEvento(Eventos eventos)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                Eventos eve = new Eventos();
                if (ModelState.IsValid)
                {
                    eve = Publicar.modificarEventos(eventos);
                    return RedirectToAction("eventoMantenimiento");
                }

                return View(eventos);
            }
            else
            {
                return RedirectToAction("getHome", "Home");
            }
            

        }

        public ActionResult eventosComentar(int? id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }
            
            return View(Publicar.listarEventosComentar(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult eventosComentar(Eventos evento, string coment)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }
            ComentariosEventos comentario = new ComentariosEventos();
            comentario.IDEvento = (int)TempData["Evento"];
            comentario.fecha = DateTime.Now;
            string correo = session.ObtenerSession("correo");
            Usuarios usuario = Usuario.getID(correo);
            comentario.IDUsuario = usuario.ID;
            comentario.mensaje = coment;
            Publicar.comentarEvento(comentario);
            return RedirectToAction("detalleEvento", new { id = (int)TempData["Evento"] });
        }

        public ActionResult detalleEvento(int id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }
            Eventos evento = Publicar.visualizarMantenimientoEventos(id);
            ViewBag.Comentarios = ComentarioEventoBean.getComents(Publicar.getComentariosEventos((int)id));
            TempData["Evento"] = id;
            return View(evento);
        }

        public ActionResult borrarEvento(int? id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            Publicar.eliminarEvento(id);
            return RedirectToAction("eventoMantenimiento");
        }

        #endregion

        #region Noticias

        public ActionResult noticiasMantenimiento()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                ViewBag.Render = true;
            }
            else
            {
                ViewBag.Render = false;
            }

            return View(Publicar.listarNoticias());
        }

        [ValidateInput(false)]
        public ActionResult agregarNoticia()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            return View();
        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult agregarNoticia(Noticias noti)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            if (ModelState.IsValid)
            {
                Publicar.AgregarNoticia(noti);
                return RedirectToAction("noticiasMantenimiento");
            }
            return View();
        }

        [ValidateInput(false)]
        public ActionResult modificarNoticia(int? id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            Noticias noti = Publicar.visualizarMantenimientoNoticias(id);

            return View(noti);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult modificarNoticia(Noticias noti)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            Noticias noticias = new Noticias();
            if (ModelState.IsValid)
            {
                noticias = Publicar.modificarNoticias(noti);
                return RedirectToAction("noticiasMantenimiento");
            }

            return View(noti);

        }

        public ActionResult noticiasComentar(int? id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }
            return View(Publicar.listarNoticiasComentar(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult noticiasComentar(Noticias noticia, string coment)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }
            ComentariosNoticias comentario = new ComentariosNoticias();
            comentario.IDNoticia = (int)TempData["Noticia"];
            comentario.fecha = DateTime.Now;
            string correo = session.ObtenerSession("correo");
            Usuarios usuario = Usuario.getID(correo);
            comentario.IDUsuario = usuario.ID;

Prototipos/Views/Publicar/agregarEvento.cshtml
@model DataContracts.Eventos

<html>
<head>
    <title>PROMETHEUS GYM</title>
    <meta charset="UTF-8">
    <meta name="title" content="PROMETHEUS MUSCLE FIT GYM">
    <meta name="description" content="Descripción de la WEB">
    <link href="~/Content/estilosBody.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Scripts/misScripts.js"></script>
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.js"></script>
    <style type="text/css">

        #summernote {
            height: 300px !important;
        }
    </style>
</head>
<body>
    <div style="margin-top:50px;">
        @using (Html.BeginForm("agregarEvento", "Publicar", FormMethod.Post, new { @class = "form summer" }))
        {
            @Html.AntiForgeryToken()
            <h2>Agregar evento</h2><br />
            <div class="col-md-1"></div>
            <div class="col-md-10">

                <div class="form-group">
                    <label class="col-md-3 control-label">Fecha de publicación</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                            @Html.EditorFor(model => model.fechaPublicacion, new { htmlAttributes = new { @id="datepicker",@class = "form-control", @style = "", @required = "required;", @type = "date" } })
                        </div>
                    </div>
                </div><br /><br /><br />

                <div class="form-group">
                    <label class="col-md-3 control-label">Fecha de evento</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                            @Html.EditorFor(model => model.fechaRealizacion, new { htmlAttributes = new { @id="datepicker2",@class = "form-control", @style = "", @required = "required;", @type = "date" } })
                        </div>
                    </div>
                </div><br /><br /><br />

                <div class="form-group">
                    <label class="col-md-3 control-label">Nombre</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", @style = "", @required = "required;", @type = "text", @autocomplete = "off" } })
                        </div>
                    </div>
                </div><br /><br /><br />

                <div class="form-group">
                    <label class="col-md-3 control-label">Costo</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            @Html.EditorFor(model => model.costo, new { htmlAttributes = new { @class = "form-control", @style = "", @required = "required;", @type = "number" } })
                        </div>
                    </div>
                </div><br /><br /><br />

                <!--<div class="form-group">
                    <label class="col-md-3 control-label">Imagen</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            Html.TextBoxFor(model => model.imagen, new { type = "file" })
                        </div>
                    </div>
                </div><br /><br /><br />-->

                <br /><br /><br />

                            <div class="form-group" style="height:250px;">

                                @Html.TextAreaFor(model => model.descripcion, new { @id = "summernote", @class = "form-control", @name = "editordata", @style = "resize:none;", @required = "required;", @type = "text" })
                                <div class="col-md-4">
                                    <button name="adduser" type="submit" class="btn btn-warning btn-block" id="contact-submit">Públicar evento</button>
                                </div>
                                <div class="col-md-4">
                                    <a class="btn btn-warning btn-block" href="javascript:history.back()"> Volver atras</a>
                                </div>
                            </div>
            </div>
            <div class="col-md-1"></div>
        }
    </div>
</body>
</html>
<script>
    window.onload = function(){
  var fecha = new Date(); //Fecha actual
  var mes = fecha.getMonth()+1; //obteniendo mes
  var dia = fecha.getDate(); //obteniendo dia
  var ano = fecha.getFullYear(); //obteniendo año
  if(dia<10)
    dia='0'+dia; //agrega cero si el menor de 10
  if(mes<10)
    mes='0'+mes //agrega cero si el menor de 10
    document.getElementById('datepicker').value = ano + "-" + mes + "-" + dia;
    document.getElementById('datepicker2').value=ano+"-"+mes+"-"+dia;
}
    $('#summernote').summernote().code().replace(/<\/?[^>]+(>|$)/g, "");
    
</script>

Prototipos/Views/Publicar/agregarNoticia.cshtml
@model DataContracts.Noticias

<html>
<head>
    <title>PROMETHEUS GYM</title>
    <meta charset="UTF-8">
    <meta name="title" content="PROMETHEUS MUSCLE FIT GYM">
    <meta name="description" content="Descripción de la WEB">
    <link href="~/Content/estilosBody.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Scripts/misScripts.js"></script>
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.js"></script>
    <style type="text/css">
        #summernote {
            height: 300px !important;
        }
    </style>
</head>
<body>
    <div style="margin-top:50px;">
        @using (Html.BeginForm("agregarNoticia", "Publicar", FormMethod.Post, new { @class = "form summer" }))
        {
            @Html.AntiForgeryToken()
            <h2>Agregar nueva noticia</h2><br />
            <div class="col-md-1"></div>
            <div class="col-md-10">

                <div class="form-group">
                    <label class="col-md-3 control-label">Fecha de publicación</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                            @Html.EditorFor(model => model.fechaRealizacion, new { htmlAttributes = new { @id="datepicker",@class = "form-control", @style = "", @required = "required;", @type = "date" } })
                        </div>
                    </div>
                </div><br /><br /><br />

                <div class="form-group">
                    <label class="col-md-3 control-label">Título de la noticia</label>
                    <div class="col-md-4 inputGroupContainer">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control", @style = "", @required = "required;", @type = "text", @autocomplete = "off" } })
                        </div>
                    </div>
                </div><br /><br /><br />

                                  <div class="form-group" style="height:250px;">
                                      @Html.TextAreaFor(model => model.contenido, new { @id = "summernote", @class = "form-control", @name = "editordata", @style = "resize:none;", @required = "required;", @type = "textarea" })
                                      <div class="col-md-4">
                                          <button name="adduser" type="submit" class="btn btn-warning btn-block" id="contact-submit">Públicar noticia</button>
                                      </div>
                                      <div class="col-md-4">
                                          <a class="btn btn-warning btn-block" href="javascript:history.back()"> Volver atras</a>
                                      </div>
                                  </div>
            </div>
            <div class="col-md-1"></div>
        }
    </div>
</body>
<script>
    window.onload = function(){
  var fecha = new Date(); //Fecha actual
  var mes = fecha.getMonth()+1; //obteniendo mes
  var dia = fecha.getDate(); //obteniendo dia
  var ano = fecha.getFullYear(); //obteniendo año
  if(dia<10)
    dia='0'+dia; //agrega cero si el menor de 10
  if(mes<10)
    mes='0'+mes //agrega cero si el menor de 10
    document.getElementById('datepicker').value = ano + "-" + mes + "-" + dia;
    document.getElementById('datepicker2').value=ano+"-"+mes+"-"+dia;
}
    $('#summernote').summernote().code().replace(/<\/?[^>]+(>|$)/g, "");
</script>
</html>

Prototipos/Views/Publicar/agregarOferta.cshtml
@model DataContracts.Ofertas
<html>
<head>
    <title>PROMETHEUS GYM</title>
    <meta charset="UTF-8">
    <meta name="title" content="PROMETHEUS MUSCLE FIT GYM">
    <meta name="description" content="Descripción de la WEB">
    <link href="~/Content/estilosBody.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Scripts/misScripts.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container" style="margin-top:50px;">
        <form class="form-horizontal" action=" " method="post" id="contact_form">
            <fieldset>
                <!-- Form Name -->
                <class style="text-align:center;">
                    @using (Html.BeginForm("agregarOferta", "Publicar", FormMethod.Post, new { @class = "form" }))
                    {
                        @Html.AntiForgeryToken()

                        <h2>Agregar oferta</h2><br />

                        <!-- Text input-->
                        <div class="form-group">
                            <label class="col-md-4 control-label">Nombre</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                                    @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control", @style = "", @required = "required;", @type = "text", @autocomplete = "off" } })
                                </div>
                            </div>
                        </div>

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Descripción</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control", @style = "", @required = "required;", @type = "text", @autocomplete = "off" } })
                                </div>
                            </div>
                        </div>

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Monto</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-phone"></i></span>
                                    @Html.EditorFor(model => model.monto, new { htmlAttributes = new { @class = "form-control", @style = "", @required = "required;", @type = "number", @autocomplete = "off" } })
                                </div>
                            </div>
                        </div>

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Descuento %</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-text-width"></i></span>
                                    @Html.EditorFor(model => model.porcentaje, new { htmlAttributes = new { @class = "form-control", @style = "", @required = "required;", @type = "number", @autocomplete = "off" } })
                                </div>
                            </div>
                        </div>

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Fecha de inicio</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                    @Html.EditorFor(model => model.fechaInicio, new { htmlAttributes = new { @id = "datepicker", @class = "form-control", @style = "", @required = "required;", @type = "date" } })
                                </div>
                            </div>
                        </div>

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Fecha de finalización</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                    @Html.EditorFor(model => model.fechaFin, new { htmlAttributes = new { @id = "datepicker2", @class = "form-control", @style = "", @required = "required;", @type = "date" } })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label"></label>
                            <div class="col-md-4">
                                <button name="adduser" type="submit" class="btn btn-warning btn-block" id="contact-submit">Publicar oferta</button>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"></label>
                            <div class="col-md-4">
                                <a class="btn btn-warning btn-block" href="javascript:history.back()"> Volver atras</a>
                            </div>
                        </div>
                    }
                </class>
            </fieldset>
        </form>
    </div>
</body>
<script>

window.onload = function(){
  var fecha = new Date(); //Fecha actual
  var mes = fecha.getMonth()+1; //obteniendo mes
  var dia = fecha.getDate(); //obteniendo dia
  var ano = fecha.getFullYear(); //obteniendo año
  if(dia<10)
    dia='0'+dia; //agrega cero si el menor de 10
  if(mes<10)
    mes='0'+mes //agrega cero si el menor de 10
    document.getElementById('datepicker').value = ano + "-" + mes + "-" + dia;
    document.getElementById('datepicker2').value=ano+"-"+mes+"-"+dia;
}

</script>
</html>

Prototipos/Views/Publicar/detalleEvento.cshtml
@model DataContracts.Eventos

<html>
<head>
    <title>PROMETHEUS GYM</title>
    <meta charset="UTF-8">
    <meta name="title" content="PROMETHEUS MUSCLE FIT GYM">
    <meta name="description" content="Descripción de la WEB">
    <link href="~/Content/estilosBody.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Scripts/misScripts.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div style="margin-top: 20px;">
        <div class="col-md-2"></div>
        <div class="col-md-8">

            <div>
                <h2>@Html.DisplayFor(model => model.nombre)</h2>
                <hr />
                <dl class="dl-horizontal">
                    <h3>
                        <dt>
                            @Html.DisplayNameFor(model => model.nombre)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.nombre)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.fechaPublicacion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.fechaPublicacion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.costo)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.costo)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.descripcion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.descripcion)
                        </dd>
                    </h3>
                </dl>
            </div>


            <hr /> <br /> <br />

            <div class="form-group">
                <label class="col-md-4 control-label"></label>
                <div class="col-md-4">
                    <a class="btn btn-warning btn-block" href="javascript:history.back()"> Volver atras</a>
                </div>
            </div>


            @using (Html.BeginForm("eventosComentar", "Publicar", FormMethod.Post, new { @class = "form summer" }))
            {
                @Html.AntiForgeryToken()
                <div class="commentBox">
                    <div class="wrapper">
                        <div class="commentBoxfloat">
                            <form id="cmnt">
                                <fieldset>
                                    <div class="form_grp">
                                        <label>Comentar</label>
                                        <textarea id="userCmnt" name="coment" placeholder="Escribir comentario"></textarea> <br /><br />
                                        <div class="form-group">
                                            <div class="col-md-4">
                                                <button name="adduser" type="submit" class="btn btn-warning btn-block" id="contact-submit">Comentar</button>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            }

        <div>
            <table class="table table-striped custab" style="min-width: 100px !important;">
                <thead>
                    <tr>
                        <th>Usuario</th>
                        <th>Mensaje</th>
                        <th>Fecha</th>
                    </tr>
                </thead>
                @foreach (var comentario in ViewBag.Comentarios)
                {
                    <tr>
                        <td>@comentario.usuario</td>
                        <td>@comentario.mensaje</td>
                        <td>@comentario.fecha</td>
                    </tr>
                }

            </table>
        </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</body>
</html>