Prototipos/Controllers/HorariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataContracts;
using Prototipos.Models;
using DataLogic;

namespace Prototipos.Controllers
{
    
    public class HorariosController : Controller
    {
        DatosSession session = new DatosSession();

        // GET: Horarios
        public ActionResult Index()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            return View();
        }

        public ActionResult horariosEntrenadorClase()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            return View();
        }

        public ActionResult horariosClienteClase(int id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            return View(Clas.getClientesClase(id));
        }

        #region Insertar

        //GET://
        public ActionResult agregarClase()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            List<SelectListItem> lst = new List<SelectListItem>();

            lst.Add(new SelectListItem { Text = "Lunes", Value = "Lunes" });
            lst.Add(new SelectListItem { Text = "Martes", Value = "Martes" });
            lst.Add(new SelectListItem { Text = "Miercoles", Value = "Miercoles" });
            lst.Add(new SelectListItem { Text = "Jueves", Value = "Jueves" });
            lst.Add(new SelectListItem { Text = "Viernes", Value = "Viernes" });
            lst.Add(new SelectListItem { Text = "Sabado", Value = "Sabado" });
            lst.Add(new SelectListItem { Text = "Domingo", Value = "Domingo" });
            ViewBag.Dias = lst;
            return View();
        }

        //POST://
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult agregarClase(Clases clases)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            if (ModelState.IsValid)
            {
                Clas.AgregarClases(clases);
                return RedirectToAction("horariosMantenimiento");
            }

            return View();
        }

        #endregion

        #region Modificar
        //GET://
        public ActionResult modificarClase(int? id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            List<SelectListItem> lst = new List<SelectListItem>();

            lst.Add(new SelectListItem { Text = "Lunes", Value = "Lunes" });
            lst.Add(new SelectListItem { Text = "Martes", Value = "Martes" });
            lst.Add(new SelectListItem { Text = "Miercoles", Value = "Miercoles" });
            lst.Add(new SelectListItem { Text = "Jueves", Value = "Jueves" });
            lst.Add(new SelectListItem { Text = "Viernes", Value = "Viernes" });
            lst.Add(new SelectListItem { Text = "Sabado", Value = "Sabado" });
            lst.Add(new SelectListItem { Text = "Domingo", Value = "Domingo" });
            ViewBag.Dias = lst;

            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            return View(Clas.visualizarClase(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //POST://
        public ActionResult modificarClase(Clases clases)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            Clases cl = new Clases();
            if (ModelState.IsValid)
            {
                cl = Clas.modificarClase(clases);
                return RedirectToAction("horariosMantenimiento");
            }

            return View(clases);
        }

        #endregion

        #region Borrar

        //GET://
        public ActionResult borrarClase(int? id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            if (id == null)
            {
                return RedirectToAction("horariosMantenimiento");
            }
            else
            {
                Clas.eliminarHorario(id);
            }

            return RedirectToAction("horariosMantenimiento");
        }

        //GET://
        public ActionResult horariosMantenimiento()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                ViewBag.Render = true;
            }
            else
            {
                ViewBag.Render = false;
            }
            List<ClasesModel> listaModel = new List<ClasesModel>();
            foreach(Clases clase in Clas.ListarMantenimiento())
            {
                ClasesModel clas = new ClasesModel();
                clas.ID = clase.ID;
                clas.nombre = clase.nombre;
                clas.dia = clase.dia;
                clas.horaInicio = clase.horaInicio.ToString("hh:mm tt");
                clas.horaFin = clase.horaFin.ToString("hh:mm tt");
                listaModel.Add(clas);
            }
            return View(listaModel);
            
        }

        public ActionResult agregarClaseCliente(int id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            string correo = session.ObtenerSession("correo");
            Usuarios usuario = Usuario.getID(correo);
            Clas.agregarRefe(usuario.ID, id);
            return RedirectToAction("horariosMantenimiento");
        }

        public ActionResult miHorario()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            string correo = session.ObtenerSession("correo");
            Usuarios usuario = Usuario.getID(correo);
            List<ClasesModel> listaModel = new List<ClasesModel>();
            foreach (Clases clase in Clas.getClasesUsuario(usuario.ID))
            {
                ClasesModel clas = new ClasesModel();
                clas.ID = clase.ID;
                clas.nombre = clase.nombre;
                clas.dia = clase.dia;
                clas.horaInicio = clase.horaInicio.ToString("hh:mm tt");
                clas.horaFin = clase.horaFin.ToString("hh:mm tt");
                listaModel.Add(clas);
            }
            return View(listaModel);

        }

        public ActionResult borrarRefe(int id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }
            string correo = session.ObtenerSession("correo");
            Usuarios usuario = Usuario.getID(correo);
            Clas.borrarReferencia(usuario.ID, id);

            return RedirectToAction("miHorario");
        }

        #endregion


    }

}

Prototipos/Views/Horarios/agregarClase.cshtml
@model DataContracts.Clases

<html>
<head>
    <title>PROMETHEUS GYM</title>
    <meta charset="UTF-8">
    <meta name="title" content="PROMETHEUS MUSCLE FIT GYM">
    <meta name="description" content="Descripción de la WEB">
    <link href="~/Content/estilosBody.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-timepicker.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/misScripts.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container" style="margin-top:50px;">
        <form class="form-horizontal" action=" " method="post" id="contact_form">
            <fieldset>
                <!-- Form Name -->
                <class style="text-align:center;">

                    @using (Html.BeginForm("agregarClase", "Horarios", FormMethod.Post, new { @class = "form-control" }))
                    {
                        @Html.AntiForgeryToken()
                        <h2>Nueva clase</h2><br />

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Nombre clase</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", @style = "", @required = "required;", @type = "text", @autocomplete = "off" } })
                                </div>
                            </div>
                        </div>

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Día de la clase</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                                    @Html.DropDownListFor(model => model.dia, (IEnumerable<SelectListItem>)ViewBag.Dias, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>


                        <!-- Text input-->

                        <div class="form-group" id="horainicio">
                            <label class="col-md-4 control-label">Hora inicio</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group bootstrap-timepicker timepicker">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                                    @Html.EditorFor(model => model.horaInicio, new { htmlAttributes = new { @id = "datepicker2", @class = "form-control input-small", @style = "", @required = "required;", @type = "time" } })
                                </div>
                            </div>
                        </div>

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Hora fin</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
                                    @Html.EditorFor(model => model.horaFin, new { htmlAttributes = new { @id = "datepicker3", @class = "form-control datepicker", @style = "", @required = "required;", @type = "time" } })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label"></label>
                            <div class="col-md-4">
                                <button name="adduser" type="submit" class="btn btn-warning btn-block" id="contact-submit">Guardar clase</button>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"></label>
                            <div class="col-md-4">
                                <a class="btn btn-warning btn-block" href="javascript:history.back()"> Volver atras</a>
                            </div>
                        </div>
                    }
                </class>
            </fieldset>
        </form>
    </div>
</body>
</html>
<script>
window.onload = function () {
        var fecha = new Date(); //Fecha actual
        var mes = fecha.getMonth() + 1; //obteniendo mes
        var dia = fecha.getDate(); //obteniendo dia
        var ano = fecha.getFullYear(); //obteniendo año
        var estado = "a.m.";
        var hora = fecha.setHours();
        var minuto = fecha.setMinutes();

        if (dia < 10) { 
            dia = '0' + dia; //agrega cero si el menor de 10
        }
        if (mes < 10) {
            mes = '0' + mes;
        }
            //agrega cero si el menor de 10
        document.getElementById('datepicker3').value = hora + ":" + minuto+ ":" + estado;
        document.getElementById('datepicker2').value = hora + ":" + minuto + ":" + estado;
        document.getElementById('datepicker').value = ano + "-" + mes + "-" + dia;
            
}
    
</script>

Prototipos/Views/Horarios/horariosClienteClase.cshtml
@model IEnumerable<DataContracts.Usuarios>

@{
    ViewBag.Title = "horarios de Cliente por Cl";
}


<!DOCTYPE html>
<html>
<head>
    <title></title>
    <title>PROMETHEUS GYM</title>
    <meta charset="UTF-8">
    <meta name="title" content="PROMETHEUS MUSCLE FIT GYM">
    <meta name="description" content="Descripción de la WEB">
    <link href="~/Content/estilosBody.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/Scripts/SweerAlert/sweetalert2.min.css" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div style="margin-top: 50px;">
        <div class="col-lg-1"></div>
            <div class="col-lg-10">
                <div class="container">
                    <h2>Horarios de los clientes</h2>

                    <p>
                        @Html.ActionLink("Create New", "Create")
                    </p>
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.cedula)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.apellido1)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.apellido2)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.correo)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.contrasena)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.tipo)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.sexo)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.telefono1)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.telefono2)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ocupacion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.estadoCivil)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.habilitado)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.fechaIngreso)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.fechaPago)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IDRutina)
                            </th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.cedula)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.apellido1)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.apellido2)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.correo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.contrasena)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.tipo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.sexo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.telefono1)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.telefono2)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ocupacion)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.estadoCivil)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.habilitado)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.fechaIngreso)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.fechaPago)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IDRutina)
                                </td>
                            </tr>

                        }


                    </table>

                    <div class="form-group">
                        <label class="col-md-4 control-label"></label>
                        <div class="col-md-4">
                            <a class="btn btn-warning btn-block" href="javascript:history.back()"> Volver atras</a>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    
</body>
</html>

Prototipos/Views/Horarios/horariosClienteClase2.cshtml
<html>
<head>
    <title>PROMETHEUS GYM</title>
    <meta charset="UTF-8">
    <meta name="title" content="PROMETHEUS MUSCLE FIT GYM">
    <meta name="description" content="Descripción de la WEB">
    <link href="~/Content/estilosBody.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Scripts/misScripts.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div style="margin-top: 50px;">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="container">
                <h2>Cliente por clase</h2><br /><br />
                <table class="table table-striped custab">
                    <thead>
                        <tr>
                            <th>Cédula</th>
                            <th>Nombre cliente</th>
                            <th>Nombre clase</th>
                            <th>Fecha</th>
                            <th>Hora inicio</th>
                            <th>Hora fin</th>
                        </tr>
                    </thead>
                    <tr>
                        <td>ForEach</td>
                        <td>ForEach</td>
                        <td>ForEach</td>
                        <td>ForEach</td>
                        <td>ForEach</td>
                        <td>ForEach</td>
                    </tr>

                </table>
                <div class="pagination">
                    <li><a href="#">Prev</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">Next</a></li>
                </div>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
</body>
</html>

Prototipos/Views/Horarios/horariosEntrenadorClase.cshtml
@model IEnumerable<Prototipos.Models.Usuarios_Clases> 
<html>
<head>
    <title>PROMETHEUS GYM</title>
    <meta charset="UTF-8">
    <meta name="title" content="PROMETHEUS MUSCLE FIT GYM">
    <meta name="description" content="Descripción de la WEB">
    <link href="~/Content/estilosBody.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Scripts/misScripts.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div style="margin-top: 50px;">
        <div class="col-lg-1"></div>
        <div class="col-lg-10">
            <div class="container">
                <h2>Entrenador por clase</h2><br /><br />
                <table class="table table-striped custab">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.Usuarios.cedula)</th>
                            <th>@Html.DisplayNameFor(model => model.Usuarios.nombre)</th>
                            <th>@Html.DisplayNameFor(model => model.Clases.nombre)</th>@* Nombre de la clase *@
                            <th>@Html.DisplayNameFor(model => model.Clases.dia)</th>
                            <th>@Html.DisplayNameFor(model => model.Clases.horaInicio)</th>
                            <th>@Html.DisplayNameFor(model => model.Clases.horaFin)</th>
                        </tr>
                    </thead>
                    @foreach (var item in Model)
                    {
                        <tr>
                        <td>@Html.DisplayFor(modeItem => item.Usuarios.cedula)</td>
                        <td>@Html.DisplayFor(modeItem => item.Usuarios.nombre)</td>
                        <td>@Html.DisplayFor(modeItem => item.Clases.nombre)</td>@* Nombre de la clase *@
                        <td>@Html.DisplayFor(modeItem => item.Clases.dia)</td>
                        <td>@Html.DisplayFor(modeItem => item.Clases.horaInicio)</td>
                        <td>@Html.DisplayFor(modeItem => item.Clases.horaFin)</td>
                    </tr>
                    }
                    

                </table>
                <div class="pagination">
                    <li><a href="#">Prev</a></li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">Next</a></li>
                </div>
            </div>
        </div>
        <div class="col-lg-1"></div>
    </div>
</body>
</html>

Prototipos/Views/Horarios/modificarClase.cshtml
@model DataContracts.Clases
<html>
<head>
    <title>PROMETHEUS GYM</title>
    <meta charset="UTF-8">
    <meta name="title" content="PROMETHEUS MUSCLE FIT GYM">
    <meta name="description" content="Descripción de la WEB">
    <link href="~/Content/estilosBody.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Scripts/misScripts.js"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container" style="margin-top:50px;">
        <form class="form-horizontal" action=" " method="post" id="contact_form">
            <fieldset>
                <!-- Form Name -->
                <class style="text-align:center;">


                    @using (Html.BeginForm("modificarClase", "Horarios", FormMethod.Post, new { @class = "form-control" }))
                    {
                        @Html.AntiForgeryToken()
                        <h2>Modificar clase</h2><br />

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Nombre clase</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control", @style = "", @required = "required;", @type = "text", @autocomplete = "off" } })
                                </div>
                            </div>
                        </div>

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Día de la clase</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                                    @Html.DropDownListFor(model => model.dia, (IEnumerable<SelectListItem>)ViewBag.Dias, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>


                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Hora inicio</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    @Html.EditorFor(model => model.horaInicio, new { htmlAttributes = new { @id = "datepicker2", @class = "form-control", @style = "", @required = "required;", @type = "time", @autocomplete = "off" } })
                                </div>
                            </div>
                        </div>

                        <!-- Text input-->

                        <div class="form-group">
                            <label class="col-md-4 control-label">Hora fin</label>
                            <div class="col-md-4 inputGroupContainer">
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    @Html.EditorFor(model => model.horaFin, new { htmlAttributes = new { @id = "datepicker3", @class = "form-control", @style = "", @required = "required;", @type = "time", @autocomplete = "off" } })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-4 control-label"></label>
                            <div class="col-md-4">
                                <button name="adduser" type="submit" class="btn btn-warning btn-block" id="contact-submit">Guardar clase</button>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label"></label>
                            <div class="col-md-4">
                                <a class="btn btn-warning btn-block" href="javascript:history.back()"> Volver atras</a>
                            </div>
                        </div>
                    }

                </class>        
            </fieldset>
        </form>
    </div>
</body>

</html>
<script>
    window.onload = function () {
        var fecha = new Date(); //Fecha actual
        var mes = fecha.getMonth() + 1; //obteniendo mes
        var dia = fecha.getDate(); //obteniendo dia
        var ano = fecha.getFullYear(); //obteniendo año
        var hora = fecha.getHours();
        var minuto = fecha.getMinutes();
        var estado = fecha.getTimezoneOffset();
        if (dia < 10)
            dia = '0' + dia; //agrega cero si el menor de 10
        if (mes < 10)
            mes = '0' + mes //agrega cero si el menor de 10
        document.getElementById('datepicker').value = ano + "-" + mes + "-" + dia;
        document.getElementById('datepicker2').value = hora + ":" + minuto;
        document.getElementById('datepicker3').value = hora + ":" + minuto;
    }
</script>