Prototipos/Controllers/EnviosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataContracts;
using DataLogic;
using Prototipos.Models;

namespace Prototipos.Controllers
{
    public class EnviosController : Controller
    {
        DatosSession session = new DatosSession();
        // GET: Envios
        public ActionResult Index()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            return View();
        }

        public ActionResult mensajeTexto()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            Usuarios usuario = Usuario.getID(session.ObtenerSession("correo"));
            List<Mensaje> lista = Envios.listarMensajes(usuario.ID);
            Dictionary<int, string> clientes = new Dictionary<int, string>();
            foreach (Usuarios user in Usuario.getAllUsers())
            {
                clientes.Add(user.ID,user.nombre + " " + user.apellido1 + " " + user.apellido2);
            }
            ViewBag.Clientes = clientes;
            return View(lista);
        }

        public ActionResult agrgarMensaje()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            List<SelectListItem> clientes = new List<SelectListItem>();
            foreach (Usuarios user in Usuario.getAllUsers())
            {
                clientes.Add(new SelectListItem { Text = user.nombre+" "+user.apellido1+" "+user.apellido2, Value = user.ID.ToString() });
            }
            ViewBag.Clientes = clientes;
            return View();
        }

        [HttpPost]
        public ActionResult agrgarMensaje(Mensaje mensaje)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            Usuarios user = Usuario.getID(session.ObtenerSession("correo"));
            mensaje.IDEmisor = user.ID;
            Envios.agregarMensaje(mensaje);
            return RedirectToAction("mensajeTexto");
        }


        public ActionResult notificacionesEnviar(int id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            return View(Publicar.listarNotificaciones(id));
        }

        public ActionResult AgregarNotificaciones()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            return View();
        }

        [HttpPost]
        public ActionResult AgregarNotificaciones(Notificaciones notificacion)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            int id=Envios.AgregarNotificaciones(notificacion);
            List<Usuarios> usuarios = Usuario.getAllUsers();
            foreach(Usuarios user in usuarios){
                referenciaUsuarios_referenciaNotificaciones referencia= new referenciaUsuarios_referenciaNotificaciones();
                referencia.IDNotificacion = id;
                referencia.IDUsuario = user.ID;
                Envios.AgregarRefe(referencia);
            }
            ViewBag.Usuarios = usuarios;
            return RedirectToAction("listaNotificaciones");
        }

        public ActionResult listaNotificaciones()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            return View(Envios.getNotificaciones());
        }

        public ActionResult UsuariosAnotificar()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            return View(Publicar.listarUsuarios());
        }

        public ActionResult deleteNotificacion(int id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            Envios.deleteNotificaciones(id);
            return RedirectToAction("listaNotificaciones");
        }

        public ActionResult updateNotificacion(int id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            return View(Envios.getNotificacion(id));
        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult updateNotificacion(Notificaciones notificacion)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            Envios.updateNotificaciones(notificacion);
            return RedirectToAction("listaNotificaciones");
        }
    }
}

Prototipos/Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataContracts;
using DataLogic;
using Prototipos.Models;

namespace Prototipos.Controllers
{
    public class PagosController : Controller
    {
        DatosSession session = new DatosSession();
        // GET: Pagos
        public ActionResult Index()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            return View();
        }

        public ActionResult pagosMantenimiento()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            Dictionary<int, int> clientes = new Dictionary<int, int>();
            foreach (Usuarios user in Usuario.getUsers().Where(x => x.tipo == "Cliente").ToList())
            {
                clientes.Add(user.ID, user.cedula);
            }
            ViewBag.Clientes = clientes;

            if (Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                ViewBag.Render = true;
                return View(Pagos.listarPagos());
            }
            else
            {
                ViewBag.Render = false;
                string correo = session.ObtenerSession("correo");
                Usuarios usuario = Usuario.getID(correo);
                return View(Pagos.listarPagos().Where(x=>x.IDUsuario== usuario.ID).ToList());
            }

            
            
        }

        public ActionResult pagosConsulta()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            return View(Seguridad.listarClientes());
        }

        public ActionResult agregarPago()
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            List<SelectListItem> clientes = new List<SelectListItem>();
            foreach(Usuarios user in Usuario.getUsers().Where(x => x.tipo == "Cliente").ToList())
            {
                clientes.Add(new SelectListItem { Text = user.cedula.ToString(), Value = user.ID.ToString() });
            }
            ViewBag.Clientes = clientes;
            return View();
        }

        [HttpPost]
        public ActionResult agregarPago(PagosRealizados pago)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            PagosRealizados pagosRealizados = new PagosRealizados();

            pagosRealizados = Pagos.AgregarPago(pago);

            return RedirectToAction("pagosMantenimiento");
        }

        public ActionResult modificarPago(int idpago)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            List<SelectListItem> clientes = new List<SelectListItem>();
            foreach (Usuarios user in Usuario.getUsers().Where(x => x.tipo == "Cliente").ToList())
            {
                clientes.Add(new SelectListItem { Text = user.cedula.ToString(), Value = user.ID.ToString() });
            }
            ViewBag.Clientes = clientes;
            
            PagosRealizados pago = Pagos.visualizarModificarPago(idpago);
            TempData["id"] = pago.ID;
            return View(pago);
        }

        [HttpPost]
        public ActionResult modificarPago(PagosRealizados pago)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            pago.ID = (int)TempData["id"];
                Pagos.modificarPago(pago);
                return RedirectToAction("pagosMantenimiento");
        }

        public ActionResult eliminarPago(int id)
        {
            if (session.ObtenerSession("correo").Equals(""))
            {
                return RedirectToAction("error404", "Home");
            }

            if (!Seguridad.isAdmin(session.ObtenerSession("correo")))
            {
                return RedirectToAction("getHome", "Home");
            }

            Pagos.eliminarPago(id);
            return RedirectToAction("pagosMantenimiento");
        }
    }
}

Prototipos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - PROMETHEUS MUSCLE FIT GYM</title>
    <link href="~/Content/estilosBody.css" rel="stylesheet" />
    <link href="~/Content/main.css" rel="stylesheet" />
    <script src="~/Scripts/misScripts.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/main.css">
</head>
<body style="padding-top:0px;">
    <div class="limiter">
        <div class="container-login100">
            <div class="container col-lg-9 col-md-9 col-sm-9 col-xs-9">
                <div class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color:transparent;">
                    <div class="navbar-header navbar-left col-lg-5" style="text-align:center;">
                        <ul style="margin-top:15px;">
                            <li class="titulo menu-item sub-menu">
                                <h1>@Html.ActionLink("Prometheus Gym", "getHome", "Home")</h1>
                            </li>
                            <li>
                                <h1 class="" style="font-family: auto; color:white;">
                                    Bienvenido: @ViewBag.User
                                    <img src="~/Imagenes/PrometheusGym.png" class="userpicture defaultuserpic" width="35" height="35" role="presentation" aria-hidden="true">
                                </h1>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="wrap-login100 col-lg-12 col-md-4 col-sm-6 col-xs-8" style="padding-top:30px;">
                <div class="container body-content">
                    @RenderBody()

                </div>
                @Scripts.Render("~/bundles/jquery")
                @Scripts.Render("~/bundles/bootstrap")
                @RenderSection("scripts", required: false)
            </div>
            <div class="col-lg-10 col-md-4 col-sm-4 col-xs-4" style="margin-top:25px;">
                <footer class="footerSection col-lg-12" style="background-color:transparent;">
                    <div class="container">
                        <br /><br /><br />
                        <div class="footerInfo" style="margin-bottom:20px;">
                            <div class="row">

                                <div class="footerContacto">
                                    <h5 style="color: white; font-size:3em; margin-bottom:15px;">Publicar</h5>

                                    <ul style="margin-top:15px;">
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Mantenimiento de eventos", "eventoMantenimiento", "Publicar")</h3>
                                        </li>
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Mantenimiento de noticias", "noticiasMantenimiento", "Publicar")</h3>
                                        </li>
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Mantenimiento de ofertas", "mantenimientoOfertas", "Publicar")</h3>
                                        </li>
                                    </ul>
                                </div>

                                <div class="footerContacto" style="margin-left:20%;">
                                    <h5 style="color: white; font-size:3em; margin-bottom:15px;">Horarios</h5>
                                    <ul style="margin-top:15px;">
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Mantenimiento de clases", "horariosMantenimiento", "Horarios")</h3>
                                        </li>
                                    </ul>
                                </div>

                                <div class="footerContacto" style="margin-left:20%;">
                                    <h5 style="color: white; font-size:3em; margin-bottom:15px;">Clientes</h5>
                                    <ul style="margin-top:15px;">
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Medidas / Historial médico", "medidasMantenimiento", "Clientes")</h3>
                                        </li>
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Rutinas", "rutinasMantenimiento", "Clientes")</h3>
                                        </li>
                                    </ul>
                                </div>


                            </div>
                        </div>
                        <div class="footerInfo" style="margin-bottom:20px;">
                            <div class="row">

                                <div class="footerContacto">
                                    <h5 style="color: white; font-size:3em; margin-bottom:15px;">Seguridad</h5>
                                    <ul style="margin-top:20px;">
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Cambiar contraseña", "seguridadCambiarContraseña", "Seguridad")</h3>
                                        </li>
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Mantenimiento de usuarios", "seguridadMantenimientoClientes", "Seguridad")</h3>
                                        </li>
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Cerrar sesión", "Index", "Home")</h3>
                                        </li>
                                    </ul>
                                </div>

                                <div class="footerContacto" style="margin-left:20%;">
                                    <h5 style="color: white; font-size:3em; margin-bottom:15px;">Pagos</h5>
                                    <ul style="margin-top:15px;">
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Mantenimiento de pagos", "pagosMantenimiento", "Pagos")</h3>
                                        </li>
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Pagos morosos", "pagosConsulta", "Pagos")</h3>
                                        </li>
                                    </ul>
                                </div>

                                <div class="footerContacto" style="margin-left:20%;">
                                    <h5 style="color: white; font-size:3em; margin-bottom:15px;">Envios</h5>
                                    <ul style="margin-top:15px;">
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Enviar notificaciones", "UsuariosAnotificar", "Envios")</h3>
                                        </li>
                                        <li class="menu-item sub-menu">
                                            <h3>@Html.ActionLink("Enviar mensaje", "mensajeTexto", "Envios")</h3>
                                        </li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </div>
</body>

</html>